import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff
import seaborn as sns
import matplotlib.pyplot as plt
import preprocessor
import helper

# --------- Load and preprocess data ----------
df = preprocessor.preprocess()
st.sidebar.title("Olympics Analysis")
user_menu = st.sidebar.radio(
    "Select an Option",
    (
        "Medal Tally",
        "Overall Analysis",
        "Country-wise Analysis",
        "Athlete-wise Analysis"
    )
)
# --------- Medal Tally ----------
if user_menu == "Medal Tally":
    st.sidebar.header("Medal Tally")
    years, countries = helper.country_year_list(df)
    selected_year = st.sidebar.selectbox("Select Year", years)
    selected_country = st.sidebar.selectbox("Select Country", countries)
    medal_tally = helper.fetch_medal_tally(df, selected_year, selected_country)
    if selected_year == 'Overall' and selected_country == 'Overall':
        st.title("Overall Medal Tally")
    if selected_year != 'Overall' and selected_country == 'Overall':
        st.title(f"Medal Tally in {selected_year} Olympics")
    if selected_year == 'Overall' and selected_country != 'Overall':
        st.title(f"Overall Performance of {selected_country}")
    if selected_year != 'Overall' and selected_country != 'Overall':
        st.title(f"{selected_country} Performance in {selected_year} Olympics")
    st.table(medal_tally)
# --------- Overall Analysis ----------
if user_menu == "Overall Analysis":
    st.title("Overall Analysis")
    editions = df['Year'].unique().shape[0] - 1
    cities = df['City'].unique().shape[0]
    sports = df['Sport'].unique().shape[0]
    events = df['Event'].unique().shape[0]
    athletes = df['Name'].unique().shape[0]
    nations = df['NOC'].unique().shape[0]
    col1, col2, col3 = st.columns(3)
    with col1:
        st.header("Editions")
        st.title(editions)
    with col2:
        st.header("Hosts")
        st.title(cities)
    with col3:
        st.header("Sports")
        st.title(sports)
    col1, col2, col3 = st.columns(3)
    with col1:
        st.header("Events")
        st.title(events)
    with col2:
        st.header("Athletes")
        st.title(athletes)
    with col3:
        st.header("Nations")
        st.title(nations)
    nations_over_time = helper.data_over_time(df, 'NOC')
    fig = px.line(nations_over_time, x="Edition", y="NOC")
    fig.update_layout(xaxis=dict(dtick=4))
    st.header("Participating Nations Over the Years")
    st.plotly_chart(fig)
    events_over_time = helper.data_over_time(df, 'Event')
    fig = px.line(events_over_time, x="Edition", y="Event")
    fig.update_layout(xaxis=dict(dtick=4))
    st.header("Events Over the Years")
    st.plotly_chart(fig)
    athletes_over_time = helper.data_over_time(df, 'Name')
    fig = px.line(athletes_over_time, x="Edition", y="Name")
    fig.update_layout(xaxis=dict(dtick=4))
    st.header("Athletes Over the Years")
    st.plotly_chart(fig)
    st.header("No. of Events Over Time (Every Sport)")
    fig, ax = plt.subplots(figsize=(20, 20))
    x = df.drop_duplicates(['Year', 'Sport', 'Event'])
    ax = sns.heatmap(x.pivot_table(index='Sport', columns='Year', values='Event', aggfunc='count').fillna(0).astype(int), annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    top_athletes = helper.most_successful_by_sport(df, 'Overall', 15)
    st.table(top_athletes)


# --------- Country-wise Analysis ----------
if user_menu == "Country-wise Analysis":
    st.title("Country-wise Analysis")
    countries = df['Country'].dropna().unique().tolist()
    countries.sort()
    selected_country = st.selectbox("Select a Country", countries)
    country_df = df[df['Country'] == selected_country]
    st.header(f"{selected_country} Medal Tally Over the Years")
    country_medal_tally = helper.yearwise_medal_tally(country_df, selected_country)
    fig = px.line(country_medal_tally, x="Year", y="Medal")
    fig.update_layout(xaxis=dict(dtick=4))
    st.plotly_chart(fig)
    st.header(f"{selected_country} Performance Heatmap")
    country_heatmap = helper.country_event_heatmap(country_df, selected_country)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_heatmap, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header(f"Top 10 Athletes of {selected_country}")
    top_athletes = helper.most_successful_country(country_df, selected_country)
    st.table(top_athletes)
# --------- Athlete-wise Analysis ----------
if user_menu == "Athlete-wise Analysis":
    st.title("Athlete-wise Analysis")
    athlete_df = df[df['Name'].notna()]
    x1 = athlete_df['Age'].dropna()
    x2 = athlete_df[athlete_df['Medal'] == 'Gold']['Age'].dropna()
    x3 = athlete_df[athlete_df['Medal'] == 'Silver']['Age'].dropna()
    x4 = athlete_df[athlete_df['Medal'] == 'Bronze']['Age'].dropna()
    fig = ff.create_distplot([x1, x2, x3, x4], ['Overall Age', 'Gold Medalist', 'Silver Medalist', 'Bronze Medalist'], show_hist=False, show_rug=False)
    fig.update_layout(autosize=False, width=800, height=600)
    st.header("Distribution of Age")
    st.plotly_chart(fig)
    sport_list = athlete_df['Sport'].unique().tolist()
    sport_list.sort()
    sport_list.insert(0, 'Overall')
    selected_sport = st.selectbox("Select a Sport", sport_list)
    x = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=x['Weight'], y=x['Height'], hue=x['Medal'], style=x['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)
    st.header("Most Successful Athletes")
    sport_list = df['Sport'].unique().tolist()
    sport_list.sort()
    selected_sport = st.selectbox("Select a Sport", sport_list)
    successful_athletes = helper.fetch_successful_athletes(df, selected_sport)
    st.table(successful_athletes)
    st.header("Country-wise Athlete Distribution")
    country_distribution = helper.country_athlete_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.heatmap(country_distribution, annot=True)
    plt.xticks(rotation=45)
    st.pyplot(fig)
    st.header("Age Distribution of Athletes")
    age_distribution = helper.age_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots(figsize=(20, 20))
    ax = sns.histplot(age_distribution, bins=30, kde=True)
    plt.xlabel("Age")
    plt.ylabel("Number of Athletes")
    plt.title(f"Age Distribution of Athletes in {selected_sport}")
    st.pyplot(fig)
    st.header("Height vs Weight Distribution")
    height_weight = helper.height_weight_distribution(athlete_df, selected_sport)
    fig, ax = plt.subplots()
    ax = sns.scatterplot(x=height_weight['Weight'], y=height_weight['Height'], hue=height_weight['Medal'], style=height_weight['Medal'], s=60)
    plt.xlabel("Weight")
    plt.ylabel("Height")
    plt.title(f"Height vs Weight Distribution in {selected_sport}")
    st.pyplot(fig)



